plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.html
  - robots.txt
  - sitemap.xml
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
  - src
